"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Indicator = void 0;
/**
 * Wraps a single tulip_rs indicator's flat napi-rs exports into a typed class.
 *
 * `S` is the napi-rs State class for this indicator (e.g. `SmaState`).
 * It defaults to `unknown` so that the class is usable before `binding.d.ts`
 * has been generated by `napi build`.
 */
class Indicator {
    constructor(name) {
        // `binding` is generated at build time by `napi build --js binding.js`.
        // We use require() so TypeScript does not try to resolve it before it exists.
        // eslint-disable-next-line @typescript-eslint/no-require-imports
        const n = require("../binding");
        const cap = name.charAt(0).toUpperCase() + name.slice(1);
        this.info = n[`${name}Info`]();
        this.indicator = n[`${name}Indicator`];
        this.minData = n[`${name}MinData`];
        this.minDataAccuracy = n[`${name}MinDataAccuracy`];
        this.simdByAssets = n[`${name}SimdByAssets`];
        this.simdByOptions = n[`${name}SimdByOptions`];
        this.State = n[`${cap}State`];
    }
}
exports.Indicator = Indicator;
