export interface IndicatorInfo {
    name: string;
    fullName: string;
    inputs: string[];
    options: string[];
    outputs: string[];
    optionalOutputs: string[];
    indicatorType: string;
    displayType: string;
}
/**
 * Wraps a single tulip_rs indicator's flat napi-rs exports into a typed class.
 *
 * `S` is the napi-rs State class for this indicator (e.g. `SmaState`).
 * It defaults to `unknown` so that the class is usable before `binding.d.ts`
 * has been generated by `napi build`.
 */
export declare class Indicator<S = unknown> {
    /** Static metadata — fetched once at construction, never changes. */
    readonly info: IndicatorInfo;
    /** Run the indicator on a batch of data. Returns `[outputs, state]`. */
    readonly indicator: (inputs: number[][], options: number[]) => [number[][], S];
    /** Minimum number of input bars required to produce at least one output bar. */
    readonly minData: (options: number[]) => number;
    /** Minimum input bars needed to achieve a given decimal accuracy. */
    readonly minDataAccuracy: (options: number[], decimals: number) => number;
    /**
     * SIMD — run N assets through the indicator in a single pass.
     * N must be 2, 4, 8, or 16.
     * `inputs` shape: `[N][INPUTS_WIDTH][data_len]`
     */
    readonly simdByAssets: (inputs: number[][][], options: number[]) => [number[][][], S[]];
    /**
     * SIMD — run N option-sets against the same asset data in a single pass.
     * N must be 2, 4, 8, or 16.
     * Absent (`undefined`) for indicators that have no options (OPTIONS_WIDTH === 0).
     */
    readonly simdByOptions?: (inputs: number[][], optionsList: number[][]) => [number[][][], S[]];
    /**
     * The napi-rs State class for this indicator.
     * Use `ti.sma.State.fromBuffer(buf)` or `ti.sma.State.fromJson(json)` to restore state.
     */
    readonly State: any;
    constructor(name: string);
}
